export const actionTypes = {
    ADD_PRODUCT_TO_CART: "ADD_PRODUCT_TO_CART",
    REMOVE_PRODUCT_FROM_CART: "REMOVE_PRODUCT_FROM_CART",
    CLEAE_CART: "CLEAE_CART",
    PRODUCTS_LOADING: "PRODUCTS_LOADING",
    PRODUCTS_FETCHED: "PRODUCTS_FETCHED",
    SET_CURRENCY: "SET_CURRENCY",
};